---
dist: xenial
language: ruby
rvm:
- 2.6.6
sudo: false
notifications:
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/645924d04dbb62cf2df4
    on_success: change
    on_failure: always
    on_start: never
cache:
  bundler: true
  yarn: true
env:
  global:
  - RUBY_GC_HEAP_GROWTH_MAX_SLOTS=300000
  - RUBY_GC_HEAP_INIT_SLOTS=600000
  - RUBY_GC_HEAP_GROWTH_FACTOR=1.25
  matrix:
  - TEST_SUITE=spec
  - TEST_SUITE=yarn:test
addons:
  postgresql: '10'
install:
- bin/setup
- bundle exec rake yarn:install
script: bundle exec rake $TEST_SUITE
after_script: bundle exec codeclimate-test-reporter
