---
:ems:
  :ems_redfish:
    :blacklisted_event_names: []
    :event_handling:
      :event_groups:

:ems_refresh:
  :redfish_ph_infra:
    :inventory_object_refresh: true

:http_proxy:
  :redfish:
    :host:
    :password:
    :port:
    :user:

:log:
  :level_redfish: info

:workers:
  :worker_base:
    :queue_worker_base:
      :ems_refresh_worker:
        :ems_refresh_worker_redfish_physical_infra: {}
    :event_catcher:
      :event_catcher_redfish: {}
